### ISSUE TITLE
Request to add iosvmata medium font style

### ISSUE THREAD

**Issue by ciscohack** [N-R-K/Iosvmata#1]
Thanks for such a great font. Can you please include a medium font style as the bold style of this font is too much bold?  This is a small request to you. Losevka have a medium-style. Also it is inspired from pragmato so can we have ligature support like pragmato.. Hoping for positive response

Thanks once again

**Comment by ciscohack** [comment]
Hello Expert, Any comment on this request

**Comment by N-R-K** [comment]
> ligature

I don't like ligatures and don't use it. So there's zero interest in supporting/maintaining it.

> medium font style

I can take a look into it the next time I update the font. But there's no guarantee when it'll happen. It might take months or maybe even more than an year.

- - -

If you need it urgently then you can customize the `toml` file in this repo and follow the Iosevka build instructions to build it yourself.

**Comment by ciscohack** [comment]
@N-R-K first thanks a lot. not urgent so take your time to rebuild next time.

I understand many do not like ligature thought to request one for your font lover .... I really loved your font... 


One last question do you use gruvbox_dark theme in screenshot it look like but can u confirm that shine the font a lot

**Comment by N-R-K** [comment]
I'm using [gruvbox8-hard](https://github.com/lifepillar/vim-gruvbox8) variant but with some personal modifications (darker `#171717` background and removed the pink color).

**Comment by ciscohack** [comment]
Thanks for the info. May, I have a copy of your modification?I really liked specially this font looks amazing.. if you remove the pink color then what you used in place of pink

so background dark you changed  from #1d2021 to #171717 right

**Comment by ciscohack** [comment]
@N-R-K my friend what colour should I use in place of ping can you please share the RGB value...thanks  ..Dark background I have changed as you suggested and I am close to yours.

**Comment by ciscohack** [comment]
@N-R-K My friend, please guide me to get the theme matches to your terminal theme what should I use in place of pink or may I have your theme copy to try... please do help

**Comment by N-R-K** [comment]
Try to be patient. Providing free service to random people on github isn't a top priority for everyone.

But with that being said, here's a tarball of my modified gruvbox8: [grubbox8-nrk.tar.gz](https://github.com/N-R-K/Iosvmata/files/12730981/grubbox8-nrk.tar.gz)

**Comment by ciscohack** [comment]
@N-R-K I so sorry my friend and thanks for it

**Comment by N-R-K** [comment]
I've decided that I don't want to put in extra work to build and maintain something that I won't be using myself. I've instead added some further instruction on how to customize the config and build the font in https://github.com/N-R-K/Iosvmata/commit/1d7e01e0458901add741692b6692eaccb6316e9a.
